version: '2.1'
services:
  postgres:
    image: postgres:9.5
    ports:
     - "5432:5432"
  appsvr:
    image: payara/server-full
    ports:
     - "8080:8080"
    volumes:
     - "./target/jakartaee8-starter.war:/opt/payara5/glassfish/domains/domain1/autodeploy/.war"
    environment:
      - "DB_SERVERNAME=localhost"
      - "DB_USER=postgres"
      - "DB_PASSWORD=bajunko13"
      - "DB_DATABASENAME=postgres"