INSERT INTO BENUTZER (ID,NAME, PASSWORT, PRIVILEGT)
VALUES (1,'test1', 'test1234567', 'false');

INSERT INTO BENUTZER (ID, NAME, PASSWORT, PRIVILEGT)
VALUES (2,'test2', 'test1234567', 'false');

INSERT INTO BENUTZER (ID,NAME, PASSWORT, PRIVILEGT)
VALUES (3,'test3', 'test1234567', 'true');